/**
 * Every page the site builds, per locale, with its SEO fields (spec "SEO and schema"). One list
 * feeds metadata (lib/seo.ts), the sitemaps, llms.txt and the build-time OG images
 * (scripts/generate-og.ts), so they can never disagree about what exists.
 *
 * Titles and descriptions are written per language, not translated. Descriptions are generated
 * from record fields for data pages and taken from hand-written copy for guides and tools, then
 * clamped to 140–155 characters.
 */
import { homeStory, toolCopy } from "./content";
import {
  getBroker,
  getBuildableLocalities,
  getCircleRateSchedules,
  getCities,
  getCurrentCircleRateSchedule,
  getPublishedProjects,
  getPublishedProjectsByCity,
  getStampDutyRules,
  getStandardPages,
  getUpdates,
} from "./data";
import { brokerIsRegistered, hasSourcedLandUse } from "./guards";
import { getGuides } from "./guides";
import {
  baseRate,
  getCurrentRateSchedule,
  getLocalityRate,
  getRowsByTehsil,
  getTehsilSummary,
  getTehsilsByCity,
  hasUniqueRateProfile,
  isRowIndexable,
  rowEffectiveFrom,
} from "./rates";
import { formatDate, formatNumber, localePath, pick, SITE_URL, type Locale } from "./i18n";
import { landUseLabels } from "./labels";
import { guideAlternate, localityAlternate, sameAlternate, type Alternate } from "./routes";
import type { Locality } from "./schemas";
import { TOOL_SLUGS } from "./tools";
import { getVillageContent, villageCopy, villageContentIndexableIds } from "./village-content";
import { getVillageNote } from "./data";
import { getFrontage, getFrontageOnlySros, getFrontageVillages } from "./frontage";
import { updateTypeLabels } from "@/components/UpdateRow";

export type PageKind =
  | "home"
  | "city"
  | "locality"
  | "circle-rates"
  /**
   * /<city>/circle-rates/<tehsil>/ — one per tehsil, indexable; an SRO known only from its khasra
   * frontage list builds here too, noindex until its rates land
   */
  | "rate-tehsil"
  /** /<city>/circle-rates/<tehsil>/<village>/ — one per row of the published list (or of a frontage list), noindex by default */
  | "rate-village"
  | "project"
  | "guide"
  | "tool"
  | "updates"
  | "update"
  | "about"
  /** hand-written standard pages whose copy is data: /privacy/, /terms/ */
  | "standard";

export type OgText = {
  /** big serif line */
  title: string;
  /** smaller line under it */
  subtitle: string;
  /** pill, e.g. price band, project status, update type */
  chip?: string;
};

export type PageEntry = {
  locale: Locale;
  kind: PageKind;
  /** site path without the locale prefix, leading and trailing slash */
  sitePath: string;
  /** locale-prefixed path */
  path: string;
  url: string;
  title: string;
  description: string;
  /** YYYY-MM-DD */
  lastmod: string;
  alternate: Alternate;
  og: OgText;
  /** /og/<locale>/<slug>-<hash>.png, generated by scripts/generate-og.ts */
  ogPath: string;
  /** Draft localities: rendered, but noindex and absent from the sitemaps and llms.txt */
  noindex: boolean;
};

const YEAR = new Date().getFullYear();
const SITE = { en: "Awadhland", hi: "अवधलैंड" } as const;
const DESC_MIN = 140;
const DESC_MAX = 155;

/**
 * Clamp to 140–155 chars. Over-long text is cut at the last sentence end that fits (word boundary
 * with an ellipsis only when no sentence fits); short text gets the locale's tail sentences.
 */
export function clampDescription(text: string, locale: Locale): string {
  // Distinct tails, longest first; each is used at most once and only when it fits.
  // The registration tail is dropped while no UP RERA number is on record: these pad short
  // descriptions across the whole site, so leaving it in would re-assert on hundreds of pages
  // the claim the titles below withhold.
  const registered = brokerIsRegistered(getBroker());
  const tails = (
    locale === "hi"
      ? ["हर आँकड़ा स्रोत और तारीख़ के साथ।", "यूपी रेरा ब्रोकर व्हाट्सऐप पर।", "फ़ीस लिखित में।", "हिंदी और अंग्रेज़ी में।"]
      : ["Every figure sourced and dated.", "UP RERA broker on WhatsApp.", "Fees in writing.", "Hindi and English."]
  ).filter((t) => registered || !/RERA|रेरा/i.test(t));
  const sentenceEnd = (s: string) => Math.max(s.lastIndexOf(". "), s.lastIndexOf("। "), s.endsWith(".") || s.endsWith("।") ? s.length - 1 : -1);
  let s = text.replace(/\s+/g, " ").trim();
  if (s.length > DESC_MAX) {
    const cut = s.slice(0, DESC_MAX + 1);
    const end = sentenceEnd(cut);
    if (end >= 90) s = cut.slice(0, end + 1).trim();
    else {
      const sp = cut.lastIndexOf(" ");
      s = `${cut.slice(0, sp > 100 ? sp : DESC_MAX).replace(/[,;:\s]+$/, "")}…`;
    }
  }
  for (const tail of tails) if (s.length < DESC_MIN && s.length + 1 + tail.length <= DESC_MAX) s = `${s} ${tail}`;
  if (s.length < DESC_MIN) {
    // Rare: no unused tail fits. Append the shortest and word-cut with an ellipsis.
    const padded = `${s} ${tails.at(-1)}`;
    const sp = padded.slice(0, DESC_MAX).lastIndexOf(" ");
    s = `${padded.slice(0, sp)}…`;
  }
  return s;
}

/** "1 entry" / "2 entries", per language. */
const n = (count: number, one: string, many: string) => `${formatNumber(count)} ${count === 1 ? one : many}`;

/** Short stable hash for OG file names, so a changed title gets a new URL and an unchanged one is not re-rendered. */
export function ogHash(og: OgText): string {
  let h = 5381;
  for (const ch of `${og.title}|${og.subtitle}|${og.chip ?? ""}`) h = ((h << 5) + h + ch.codePointAt(0)!) >>> 0;
  return h.toString(36).padStart(7, "0").slice(0, 8);
}

const ogFile = (locale: Locale, slug: string, og: OgText) => `/og/${locale}/${slug}-${ogHash(og)}.png`;

const priceBandLabel: Record<NonNullable<Locality["priceBand"]>, Record<Locale, string>> = {
  low: { en: "Low band", hi: "कम दाम" },
  mid: { en: "Mid band", hi: "मध्यम दाम" },
  high: { en: "High band", hi: "ऊँचा दाम" },
  premium: { en: "Premium", hi: "प्रीमियम" },
};

const cache = new Map<Locale, PageEntry[]>();

export function getPages(locale: Locale): PageEntry[] {
  const hit = cache.get(locale);
  if (hit) return hit;
  const hi = locale === "hi";
  const site = SITE[locale];
  const broker = getBroker();
  const reraOk = brokerIsRegistered(broker);
  const cities = getCities();
  const localities = getBuildableLocalities(locale).buildable;
  const projects = getPublishedProjects();
  const updates = getUpdates();
  const guides = getGuides(locale);
  const entries: PageEntry[] = [];
  const add = (e: Omit<PageEntry, "locale" | "path" | "url" | "ogPath" | "description" | "noindex"> & { description: string; ogSlug: string; noindex?: boolean }) => {
    const path = localePath(locale, e.sitePath);
    entries.push({
      locale,
      kind: e.kind,
      sitePath: e.sitePath,
      path,
      url: `${SITE_URL}${path}`,
      title: e.title,
      description: clampDescription(e.description, locale),
      lastmod: e.lastmod,
      alternate: e.alternate,
      og: e.og,
      ogPath: ogFile(locale, e.ogSlug, e.og),
      noindex: e.noindex ?? false,
    });
  };
  const newest = (dates: string[]) => dates.sort().at(-1) ?? "2026-01-01";

  /* home */
  const story = homeStory[locale];
  add({
    kind: "home",
    sitePath: "/",
    title: reraOk
      ? hi
        ? `अयोध्या, लखनऊ, गोरखपुर में ज़मीन: सर्किल रेट, प्लॉट, रेरा ब्रोकर · ${site}`
        : `Land in Ayodhya, Lucknow and Gorakhpur: rates, plots, a RERA broker · ${site}`
      : hi
        ? `अयोध्या, लखनऊ, गोरखपुर में ज़मीन: सर्किल रेट, प्लॉट, स्थानीय ब्रोकर · ${site}`
        : `Land in Ayodhya, Lucknow and Gorakhpur: rates, plots, a local broker · ${site}`,
    description: hi
      ? `अवध के हर इलाक़े का सर्किल रेट, माँगा जा रहा दाम, दूरी और सरकारी प्रोजेक्ट, स्रोत और तारीख़ के साथ। फिर व्हाट्सऐप पर ${reraOk ? "यूपी रेरा पंजीकृत" : "स्थानीय"} ब्रोकर।`
      : `Circle rates, asking prices, distances and government projects for every locality in Awadh, each with a source and a date. Then a ${reraOk ? "RERA" : "local"} broker on WhatsApp.`,
    lastmod: newest([...cities, ...localities, ...projects, ...updates].map((r) => r.updatedAt)),
    alternate: sameAlternate(locale, "/"),
    og: { title: `${story.hero.title} ${story.hero.accent}`, subtitle: hi ? "अयोध्या · लखनऊ · गोरखपुर" : "Ayodhya · Lucknow · Gorakhpur" },
    ogSlug: "home",
  });

  /* about */
  add({
    kind: "about",
    sitePath: "/about/",
    title: reraOk
      ? hi
        ? `${site} के बारे में: यूपी रेरा पंजीकृत ब्रोकर और डेटा कैसे जुटाया जाता है`
        : `About ${site}: a UP RERA-registered broker and how the data is sourced`
      : hi
        ? `${site} के बारे में: इसे कौन चलाता है और डेटा कैसे जुटाया जाता है`
        : `About ${site}: who runs it and how the data is sourced`,
    description: hi
      ? `${pick(locale, broker.name, broker.nameHi)}, ${broker.yearsActive} वर्ष से अवध की ज़मीन में। हर रेट, दूरी और प्रोजेक्ट का स्रोत और तारीख़; फ़ीस लिखित में; समीक्षाएँ जैसी गूगल पर लिखी गईं।`
      : `${pick(locale, broker.name, broker.nameHi)}, ${broker.yearsActive} years in Awadh land. How every rate, distance and project is sourced and dated, fees in writing, reviews shown as written on Google.`,
    lastmod: broker.updatedAt,
    alternate: sameAlternate(locale, "/about/"),
    og: {
      title: hi ? "हमारे बारे में" : "About Awadhland",
      subtitle: pick(locale, broker.name, broker.nameHi),
      chip: reraOk ? "UP RERA" : `${broker.yearsActive} ${hi ? "वर्ष" : "years"}`,
    },
    ogSlug: "about",
  });

  /* standard pages (privacy, terms) — copy lives in data/standardPages.json */
  for (const sp of getStandardPages()) {
    add({
      kind: "standard",
      sitePath: sp.sitePath,
      title: `${pick(locale, sp.title, sp.titleHi)} · ${site}`,
      description: pick(locale, sp.description, sp.descriptionHi),
      lastmod: sp.updatedAt,
      alternate: sameAlternate(locale, sp.sitePath),
      og: { title: pick(locale, sp.title, sp.titleHi), subtitle: pick(locale, sp.lede, sp.ledeHi) },
      ogSlug: `standard--${sp.id}`,
    });
  }

  /* cities */
  for (const c of cities) {
    const name = pick(locale, c.name, c.nameHi);
    const cityLocalities = localities.filter((l) => l.cityId === c.id);
    const ranges = cityLocalities.flatMap((l) => (l.askingRange ? [l.askingRange] : []));
    const range = ranges.length ? `₹${formatNumber(Math.min(...ranges.map((r) => r.low)))}–${formatNumber(Math.max(...ranges.map((r) => r.high)))}` : null;
    const projectCount = getPublishedProjectsByCity(c.id).length;
    add({
      kind: "city",
      sitePath: `/${c.id}/`,
      title: hi ? `${name} में ज़मीन: सर्किल रेट, इलाक़े और प्रोजेक्ट ${YEAR} · ${site}` : `${name} land: circle rates, localities and projects ${YEAR} · ${site}`,
      description: hi
        ? `${name} के ${n(cityLocalities.length, "इलाक़े", "इलाक़ों")} का सर्किल रेट। ${range ? `माँगा जा रहा दाम ${range} प्रति वर्ग फ़ुट। ` : ""}${n(projectCount, "सरकारी प्रोजेक्ट", "सरकारी प्रोजेक्ट")}, दाम का रुझान और ब्रोकर की बात।`
        : `Circle rates for ${n(cityLocalities.length, "locality", "localities")} in ${name}. ${range ? `Asking ${range} per sq ft. ` : ""}${n(projectCount, "government project", "government projects")}, a price trend and the broker's note.`,
      lastmod: newest([c.updatedAt, ...cityLocalities.map((l) => l.updatedAt)]),
      alternate: sameAlternate(locale, `/${c.id}/`),
      og: { title: name, subtitle: hi ? `${cityLocalities.length} इलाक़े · ${projectCount} प्रोजेक्ट` : `${cityLocalities.length} localities · ${projectCount} projects`, chip: range ? `${range} ${hi ? "प्रति वर्ग फ़ुट" : "per sq ft"}` : undefined },
      ogSlug: c.id,
    });

    /* circle rates */
    const schedule = getCurrentCircleRateSchedule(c.id);
    // The hub also builds on the full transcribed list alone: Lucknow has 1,449 real rows but its
    // locality-level seed is withheld, and without the hub every one of its village pages would
    // be orphaned behind a page that refused to build.
    const fullList = getCurrentRateSchedule(c.id);
    if (schedule || fullList) {
      /*
       * The description counts whichever the city actually has. Ayodhya has both and is described
       * by its sourced localities; Lucknow has only the transcribed list, so it is described by
       * its rows and SROs. Counting localities for Lucknow would have quoted the number of seeded
       * entries the page deliberately does not show.
       */
      const effective = schedule?.effectiveFrom ?? fullList!.effectiveFrom;
      const sroCount = fullList ? new Set(fullList.rows.map((r) => r.sro)).size : 0;
      const description = schedule
        ? hi
          ? `${name} की ${n(schedule.rates.length, "इलाक़े", "इलाक़ों")} की सर्किल रेट सूची, ${formatDate(effective, locale)} से लागू। रिहायशी, व्यावसायिक और कृषि दरें, स्टाम्प ड्यूटी कैलकुलेटर और संशोधन इतिहास।`
          : `${name} circle-rate schedule for ${n(schedule.rates.length, "locality", "localities")}, effective ${formatDate(effective, locale)}. Residential, commercial, agricultural rates, stamp duty calculator, revision history.`
        : hi
          ? `${name} की प्रकाशित मूल्यांकन सूची: ${n(fullList!.rows.length, "पंक्ति", "पंक्तियाँ")}, ${n(sroCount, "एसआरओ", "एसआरओ")}, ${formatDate(effective, locale)} से लागू। भूमि, व्यावसायिक और निर्माण दरें, स्टाम्प ड्यूटी कैलकुलेटर।`
          : `${name} published valuation list: ${n(fullList!.rows.length, "row", "rows")} across ${n(sroCount, "sub-registrar office", "sub-registrar offices")}, effective ${formatDate(effective, locale)}. Land, commercial and construction rates, stamp duty calculator.`;

      add({
        kind: "circle-rates",
        sitePath: `/${c.id}/circle-rates/`,
        title: hi ? `${name} सर्किल रेट ${YEAR}: सूची, लागू तारीख़, स्टाम्प ड्यूटी · ${site}` : `${name} circle rates ${YEAR}: schedule, effective date, stamp duty · ${site}`,
        description,
        lastmod: newest([schedule?.updatedAt ?? fullList!.updatedAt, ...getStampDutyRules().map((r) => r.updatedAt)]),
        alternate: sameAlternate(locale, `/${c.id}/circle-rates/`),
        og: {
          title: hi ? `${name} सर्किल रेट` : `${name} circle rates`,
          subtitle: `${hi ? "लागू" : "Effective"} ${formatDate(effective, locale)}`,
          chip: schedule
            ? `${schedule.rates.length} ${hi ? "इलाक़े" : "localities"}`
            : `${formatNumber(fullList!.rows.length)} ${hi ? "पंक्तियाँ" : "rows"}`,
        },
        ogSlug: `${c.id}--circle-rates`,
      });
    }

    /* tehsil rate pages and the village rows under them (spec Templates 5a and 5b) */
    const rateSchedule = getCurrentRateSchedule(c.id);
    if (rateSchedule) {
      const referenced = new Set(localities.filter((l) => l.status === "live").flatMap((l) => (l.rateRefs ?? []).map((r) => r.rateRowId)));
      for (const tehsil of getTehsilsByCity(c.id)) {
        // An SRO whose list has not been transcribed gets no page. It is named on the city hub as
        // pending, which says the district has more SROs than we have rates for; a page of its own
        // would have nothing on it. Checked explicitly rather than relying on rowCount, so a stray
        // row could never quietly publish one.
        if (tehsil.ratesStatus === "pending") continue;
        const summary = getTehsilSummary(c.id, tehsil.id);
        if (!summary || summary.rowCount === 0) continue;
        const tName = pick(locale, tehsil.name, tehsil.nameHi);
        const band =
          summary.minNonAgri !== null && summary.maxNonAgri !== null
            ? `₹${formatNumber(summary.minNonAgri)}–${formatNumber(summary.maxNonAgri)}`
            : null;

        add({
          kind: "rate-tehsil",
          sitePath: `/${c.id}/circle-rates/${tehsil.id}/`,
          title: hi
            ? `${tName} तहसील सर्किल रेट ${YEAR}: सभी ${formatNumber(summary.rowCount)} गाँव · ${site}`
            : `${tName} tehsil circle rates ${YEAR}: all ${formatNumber(summary.rowCount)} villages · ${name}`,
          description: hi
            ? `${tName} तहसील (${tehsil.sroNameHi}) के ${n(summary.rowCount, "गाँव", "गाँवों")} की पूरी सर्किल रेट सूची, ${formatDate(rateSchedule.effectiveFrom, locale)} से लागू। ज़मीन, व्यावसायिक और कृषि दरें${band ? `, ज़मीन ${band} प्रति वर्ग मीटर` : ""}।`
            : `The full circle-rate list for ${n(summary.rowCount, "village", "villages")} in ${tName} tehsil (${tehsil.sroName}), effective ${formatDate(rateSchedule.effectiveFrom, locale)}. Land, commercial and agricultural rates${band ? `, land ${band} per sq m` : ""}.`,
          lastmod: rateSchedule.updatedAt,
          alternate: sameAlternate(locale, `/${c.id}/circle-rates/${tehsil.id}/`),
          og: {
            title: hi ? `${tName} सर्किल रेट` : `${tName} circle rates`,
            subtitle: `${hi ? "लागू" : "Effective"} ${formatDate(rateSchedule.effectiveFrom, locale)}`,
            chip: `${formatNumber(summary.rowCount)} ${hi ? "गाँव" : "villages"}`,
          },
          ogSlug: `${c.id}--circle-rates--${tehsil.id}`,
        });

        for (const row of getRowsByTehsil(c.id, tehsil.id)) {
          /*
           * Step 9b. The written content carries a title and meta description per language; they
           * win over the generated pair because they were written against the row's own figures.
           *
           * Indexing has three ways in: the content's own indexable list (866 rows whose rate
           * profile is shared by three villages or fewer, or that a main road passes through, or
           * that are urban mohallas of Ayodhya city), a broker note, which is the one thing on
           * these pages the schedule cannot say, or a live locality already pointing at the row.
           * Everything else builds and ships noindex.
           */
          const vc = getVillageContent(row.id);
          const vcopy = vc ? villageCopy(vc, locale) : undefined;
          /*
           * Written copy, a broker note or a live locality opens a row to search. Failing all
           * three, a row is indexable only if its figures are not repeated by another row of the
           * same SRO -- which is the only test a list with no written content can offer, and is
           * what keeps Lucknow from shipping 1,449 noindex pages or 1,449 near-duplicates.
           */
          const indexable =
            villageContentIndexableIds().has(row.id) ||
            Boolean(getVillageNote(row.id)) ||
            isRowIndexable(row.id, referenced.has(row.id)) ||
            hasUniqueRateProfile(c.id, row.id);
          add({
            kind: "rate-village",
            sitePath: `/${c.id}/circle-rates/${tehsil.id}/${row.slug}/`,
            title:
              vcopy?.title ??
              (hi ? `${row.nameHi} सर्किल रेट ${YEAR} · ${tName}, ${name}` : `${row.nameEn} circle rate ${YEAR} · ${tName}, ${name}`),
            description:
              vcopy?.metaDescription ??
              (hi
              ? `${row.nameHi} (${row.nameEn}), ${tName} तहसील। सर्किल रेट ₹${formatNumber(baseRate(row))} प्रति वर्ग मीटर ${rateSchedule.roadBands[0].labelHi} चौड़ी सड़क पर${row.commercial ? `, दुकान ₹${formatNumber(row.commercial.shop)} प्रति वर्ग मीटर` : ""}। ${formatDate(rowEffectiveFrom(rateSchedule, row.sro), locale)} से लागू, मुद्रित पृष्ठ ${row.page}।`
              : `${row.nameEn} (${row.nameHi}), ${tName} tehsil. Circle rate ₹${formatNumber(baseRate(row))} per sq m on a road ${rateSchedule.roadBands[0].labelEn.toLowerCase()}${row.commercial ? `, shop ₹${formatNumber(row.commercial.shop)} per sq m` : ""}. Effective ${formatDate(rowEffectiveFrom(rateSchedule, row.sro), locale)}, printed page ${row.page}.`),
            lastmod: rateSchedule.updatedAt,
            alternate: sameAlternate(locale, `/${c.id}/circle-rates/${tehsil.id}/${row.slug}/`),
            // Village pages share their tehsil's OG image: 3,260 near-identical cards would add
            // nothing and would have to be rendered on every clean build.
            og: {
              title: hi ? `${tName} सर्किल रेट` : `${tName} circle rates`,
              subtitle: `${hi ? "लागू" : "Effective"} ${formatDate(rateSchedule.effectiveFrom, locale)}`,
              chip: `${formatNumber(summary.rowCount)} ${hi ? "गाँव" : "villages"}`,
            },
            ogSlug: `${c.id}--circle-rates--${tehsil.id}`,
            noindex: !indexable,
          });
        }
      }
    }

    /*
     * SROs whose rate list has not arrived but whose khasra frontage list has (Sadar-4, Bakshi Ka
     * Talab, Malihabad). An SRO page listing its villages, and a page per village with its frontage
     * counts, the list's remarks and a link to the plot check. All noindex until the rates land:
     * without them a village page is a list of counts, which is useful to someone who arrived
     * looking for that village and thin to a search engine.
     */
    const frontage = getFrontage(c.id);
    for (const sro of frontage ? getFrontageOnlySros(c.id) : []) {
      const tehsil = getTehsilsByCity(c.id).find((t) => t.id === sro)!;
      const tName = pick(locale, tehsil.name, tehsil.nameHi);
      const villages = getFrontageVillages(c.id, sro);
      const og: OgText = {
        title: hi ? `${tName}: सड़क से लगे खसरा` : `${tName}: khasra frontage list`,
        subtitle: hi ? "सर्किल रेट सूची की प्रतीक्षा" : "Circle rates awaited",
        chip: `${formatNumber(villages.length)} ${hi ? "गाँव" : "villages"}`,
      };
      add({
        kind: "rate-tehsil",
        sitePath: `/${c.id}/circle-rates/${sro}/`,
        title: hi
          ? `${tName} के ${formatNumber(villages.length)} गाँव: सड़क और आबादी से लगे खसरा नंबर · ${site}`
          : `${tName} villages: which khasra plots front a road or the abadi · ${name}`,
        description: hi
          ? `${tName} (${tehsil.sroNameHi}) के ${n(villages.length, "गाँव", "गाँवों")} की सूची, हर गाँव के राजमार्ग, जनपदीय मार्ग, सम्पर्क मार्ग और आबादी से लगे खसरा नंबरों के साथ। इस एसआरओ की सर्किल रेट सूची अभी आनी है।`
          : `All ${n(villages.length, "village", "villages")} under ${tehsil.sroName}, with how many khasra plots in each sit on a highway, a district road, a link road or next to the abadi. Circle rates awaited.`,
        lastmod: frontage!.updatedAt,
        alternate: sameAlternate(locale, `/${c.id}/circle-rates/${sro}/`),
        og,
        ogSlug: `${c.id}--circle-rates--${sro}`,
        noindex: true,
      });
      for (const v of villages) {
        const counts = v.counts;
        add({
          kind: "rate-village",
          sitePath: `/${c.id}/circle-rates/${sro}/${v.slug}/`,
          title: hi
            ? `${v.nameHi} खसरा सूची: सड़क और आबादी से लगे गाटे · ${tName}, ${name}`
            : `${v.nameEn} khasra list: plots on a road or next to the abadi · ${tName}, ${name}`,
          description: hi
            ? `${v.nameHi}, ${tName} तहसील। राजमार्ग पर ${counts.nh}, जनपदीय मार्ग पर ${counts.district}, सम्पर्क मार्ग पर ${counts.link} और आबादी से लगे ${counts.abadi} खसरा। अपना खसरा नंबर जाँचें।`
            : `${v.nameEn} (${v.nameHi}), ${tName}. Khasra plots listed on a highway: ${counts.nh}, district road: ${counts.district}, link road: ${counts.link}, next to the abadi: ${counts.abadi}. Check your plot.`,
          lastmod: frontage!.updatedAt,
          alternate: sameAlternate(locale, `/${c.id}/circle-rates/${sro}/${v.slug}/`),
          // Shares its SRO page's card, as the rate villages share their tehsil's.
          og,
          ogSlug: `${c.id}--circle-rates--${sro}`,
          noindex: true,
        });
      }
    }

    /* localities */
    for (const l of cityLocalities) {
      const lname = pick(locale, l.name, l.nameHi);
      // From the published list where the locality is mapped into it, else the legacy field.
      // The thin-page guard requires one or the other, so this is always defined here.
      const r = getLocalityRate(l)!;
      const anchors = c.anchors.slice(0, 2).map((a) => pick(locale, a.name, a.nameHi)).join(hi ? " और " : " and ");
      add({
        kind: "locality",
        sitePath: `/${c.id}/${l.id}/`,
        title: hi ? `${lname} में जमीन का रेट, प्लॉट और सर्किल रेट ${YEAR}` : `${lname} land rate, plots and circle rate ${YEAR} · ${name}`,
        description: hi
          ? `${lname}, ${name}। सर्किल रेट ₹${formatNumber(r.residential)} प्रति वर्ग मीटर रिहायशी, ${formatDate(r.effectiveFrom, locale)} से। ${l.askingRange ? `माँगा जा रहा दाम ₹${formatNumber(l.askingRange.low)}–${formatNumber(l.askingRange.high)} प्रति वर्ग फ़ुट। ` : ""}${hasSourcedLandUse(l) ? `भू-उपयोग ${landUseLabels[l.landUse!].hi}। ` : ""}${anchors} तक दूरी, पास के प्रोजेक्ट।`
          : `${lname}, ${name}. Circle rate ₹${formatNumber(r.residential)} per sq m residential, effective ${formatDate(r.effectiveFrom, locale)}. ${l.askingRange ? `Asking ₹${formatNumber(l.askingRange.low)}–${formatNumber(l.askingRange.high)} per sq ft. ` : ""}${hasSourcedLandUse(l) ? `Land use: ${landUseLabels[l.landUse!].en.toLowerCase()}. ` : ""}Distances to ${anchors}, projects nearby.`,
        lastmod: l.updatedAt,
        alternate: localityAlternate(locale, c.id, l.id),
        og: {
          title: lname,
          subtitle: `${name} · ₹${formatNumber(r.residential)} ${hi ? "प्रति वर्ग मीटर सर्किल रेट" : "per sq m circle rate"}`,
          chip: l.priceBand ? priceBandLabel[l.priceBand][locale] : undefined,
        },
        ogSlug: `${c.id}--${l.id}`,
        noindex: l.status === "draft",
      });
    }
  }

  /* projects */
  for (const p of projects) {
    const c = cities.find((x) => x.id === p.cityId);
    const cname = c ? pick(locale, c.name, c.nameHi) : p.cityId;
    const pname = pick(locale, p.name, p.nameHi);
    add({
      kind: "project",
      sitePath: `/projects/${p.id}/`,
      title: hi ? `${pname}: स्थिति, समयरेखा और ज़मीन पर असर · ${cname}` : `${pname}: status, timeline and effect on land · ${cname}`,
      description: `${pick(locale, p.description, p.descriptionHi)[0]}`,
      lastmod: p.updatedAt,
      alternate: sameAlternate(locale, `/projects/${p.id}/`),
      og: { title: pname, subtitle: `${cname} · ${p.agency === "other" ? (p.agencyName ?? "") : p.agency}`, chip: p.status.replace(/-/g, " ") },
      ogSlug: `project--${p.id}`,
    });
  }

  /* guides */
  for (const g of guides) {
    const fm = g.frontmatter;
    add({
      kind: "guide",
      sitePath: `/guides/${fm.slug}/`,
      title: fm.title.length > 55 ? fm.title : `${fm.title} · ${site}`,
      description: fm.summary,
      lastmod: fm.updatedAt,
      alternate: guideAlternate(locale, fm.pairedSlug, fm.cityIds),
      og: { title: fm.title, subtitle: `${g.readTimeMin} ${hi ? "मिनट" : "min read"} · ${formatDate(fm.updatedAt, locale)}`, chip: hi ? "गाइड" : "Guide" },
      ogSlug: `guide--${fm.slug}`,
    });
  }

  /* tools */
  const toolsLastmod = newest([...getCircleRateSchedules().map((s) => s.updatedAt), ...getStampDutyRules().map((r) => r.updatedAt)]);
  for (const slug of TOOL_SLUGS) {
    const copy = toolCopy[locale][slug];
    add({
      kind: "tool",
      sitePath: `/tools/${slug}/`,
      title: `${copy.title} · ${site}`,
      description: copy.intro,
      lastmod: toolsLastmod,
      alternate: sameAlternate(locale, `/tools/${slug}/`),
      og: { title: copy.title, subtitle: hi ? "मुफ़्त टूल · कोई साइनअप नहीं" : "Free tool · no signup", chip: hi ? "टूल" : "Tool" },
      ogSlug: `tool--${slug}`,
    });
  }

  /* updates */
  add({
    kind: "updates",
    sitePath: "/updates/",
    title: hi ? `अवध में ज़मीन की सूचनाएँ: सर्किल रेट, मास्टर प्लान, रेरा, प्रोजेक्ट · ${site}` : `Land notices for Awadh: circle rates, master plans, RERA, projects · ${site}`,
    description: hi
      ? `अयोध्या, लखनऊ और गोरखपुर में ज़मीन को हिलाने वाली हर सरकारी सूचना, तारीख़, एजेंसी और सरल सारांश के साथ। ${n(updates.length, "एंट्री", "एंट्री")}, शहर और प्रकार से छाँटें।`
      : `Every government notice that moves land in Ayodhya, Lucknow and Gorakhpur, with date, agency and a plain-language summary. ${n(updates.length, "entry", "entries")}, filterable by city and type.`,
    lastmod: newest(updates.map((u) => u.updatedAt)),
    alternate: sameAlternate(locale, "/updates/"),
    og: { title: hi ? "अपडेट" : "Updates", subtitle: hi ? "अवध में ज़मीन को हिलाने वाली हर सूचना" : "Every notice that moves land in Awadh", chip: `${updates.length} ${hi ? "एंट्री" : "entries"}` },
    ogSlug: "updates",
  });
  for (const u of updates) {
    const title = pick(locale, u.title, u.titleHi);
    const cityNames = u.cityIds.map((id) => { const c = cities.find((x) => x.id === id); return c ? pick(locale, c.name, c.nameHi) : id; });
    add({
      kind: "update",
      sitePath: `/updates/${u.id}/`,
      title: title.length > 55 ? title : `${title} · ${site}`,
      description: pick(locale, u.summary, u.summaryHi)[0],
      lastmod: u.updatedAt,
      alternate: sameAlternate(locale, `/updates/${u.id}/`),
      og: { title, subtitle: `${formatDate(u.date, locale)} · ${cityNames.join(", ")}`, chip: updateTypeLabels[u.type][locale] },
      ogSlug: `update--${u.id}`,
    });
  }

  cache.set(locale, entries);
  return entries;
}

/**
 * Indexed by path. Every page calls this once from generateMetadata, and the rate-village pages
 * take the list past 3,000 entries per locale, so a linear scan here is quadratic over the build.
 */
const byPath = new Map<Locale, Map<string, PageEntry>>();

export function getPage(locale: Locale, sitePath: string): PageEntry | undefined {
  let index = byPath.get(locale);
  if (!index) {
    index = new Map(getPages(locale).map((p) => [p.sitePath, p]));
    byPath.set(locale, index);
  }
  return index.get(sitePath);
}

/** Both locales, English first. */
export const getAllPages = () => [...getPages("en"), ...getPages("hi")];

/** Pages that may be indexed: everything except draft localities. Sitemaps and llms.txt use this. */
export const getIndexablePages = (locale: Locale) => getPages(locale).filter((p) => !p.noindex);

/**
 * Site paths that actually build in this locale.
 *
 * The footer and nav link only what is in here, so a page the spec lists but that has not been
 * built yet is simply not advertised rather than shipped as a 404 on all 3,300 pages.
 * scripts/check-links.ts fails the build if anything slips through anyway.
 */
export const builtSitePaths = (locale: Locale) => new Set(getPages(locale).map((p) => p.sitePath));
