/**
 * Loaders and lookups for the full published rate lists (Step 9, section A).
 *
 * data/rates/<city>-<effectiveFrom>.json holds one published schedule each: every village row and
 * every road-segment row exactly as printed. A revision is a new file, so the imports below are
 * the list of schedules the site knows about — add a line when a new list is transcribed.
 * Explicit imports rather than a directory scan because `output: 'export'` bundles these at build
 * and a variable require would not resolve.
 *
 * Units are never converted here. lib/units.ts does display conversion; storage stays as published.
 */
import { z } from "zod";
import ayodhya20250607 from "../data/rates/ayodhya-2025-06-07.json";
import lucknow20250801 from "../data/rates/lucknow-2025-08-01.json";
import indexableJson from "../data/rates/indexable.json";
import tehsilsJson from "../data/tehsils.json";
import unitsJson from "../data/units.json";
import valuationRulesJson from "../data/valuationRules.json";
import {
  indexableRatesFileSchema,
  rateScheduleSchema,
  tehsilsFileSchema,
  unitsFileSchema,
  valuationRulesFileSchema,
  type RateRow,
  type RateSchedule,
  type RoadBand,
  type RoadSegmentRow,
  type Tehsil,
} from "./schemas";
import villageSlugs from "../data/villageSlugs.json";

function parse<T>(what: string, schema: z.ZodType<T>, raw: unknown): T {
  const result = schema.safeParse(raw);
  if (!result.success) throw new Error(`Invalid data in ${what}:\n${z.prettifyError(result.error)}`);
  return result.data;
}

/** Every published schedule the site knows about. Add a line per new transcribed list. */
/**
 * The written page content carries a hand-checked romanisation of every village name, and it wins
 * over the transliteration lib/devanagari.ts produced at import: 378 of the 1,630 slugs differ,
 * nearly all of them corrections (amova to amowa, karaundimaphi to karaundimafi). Applying it here
 * rather than at each caller means the route params, the page registry, every internal link and
 * the lookup by slug all agree by construction. scripts/build-village-redirects.ts writes a 301
 * from each superseded slug, so nothing that was linked breaks.
 *
 * The slug and name come from data/villageSlugs.json, generated by scripts/build-village-index.ts,
 * rather than from the content file itself: this module is reachable from a client component
 * through lib/data and lib/tools, and importing the 20 MB content here put all of it into the
 * browser bundle. The prose lives in lib/village-content.ts, which stays server-side.
 */
function withContentNames(s: RateSchedule): RateSchedule {
  return {
    ...s,
    rows: s.rows.map((row) => {
      const c = (villageSlugs as Record<string, { slug: string; nameEn: string }>)[row.id];
      return c ? { ...row, slug: c.slug, nameEn: c.nameEn } : row;
    }),
  };
}

const schedules: RateSchedule[] = [
  withContentNames(parse("data/rates/ayodhya-2025-06-07.json", rateScheduleSchema, ayodhya20250607)),
  // Lucknow has no written page content yet, so no slug override: its names come from the
  // transliterator at import, as Ayodhya&apos;s did before the content landed.
  parse("data/rates/lucknow-2025-08-01.json", rateScheduleSchema, lucknow20250801),
];

const tehsils = parse("data/tehsils.json", tehsilsFileSchema, tehsilsJson);
const units = parse("data/units.json", unitsFileSchema, unitsJson);
const valuationRules = parse("data/valuationRules.json", valuationRulesFileSchema, valuationRulesJson);
const indexable = parse("data/rates/indexable.json", indexableRatesFileSchema, indexableJson);

/* -------------------------------------------------------------------- schedules */

export const getRateSchedules = () => schedules;

/** Newest first; [0] is the schedule in force. */
export const getRateSchedulesByCity = (cityId: string) =>
  schedules.filter((s) => s.cityId === cityId).sort((a, b) => b.effectiveFrom.localeCompare(a.effectiveFrom));

export const getCurrentRateSchedule = (cityId: string): RateSchedule | undefined => getRateSchedulesByCity(cityId)[0];

/** Cities that have a full transcribed list, so the tehsil and village pages can build. */
export const getCitiesWithRateList = () => [...new Set(schedules.map((s) => s.cityId))];

/* ---------------------------------------------------------------------- tehsils */

export const getTehsils = () => tehsils;
export const getTehsilsByCity = (cityId: string) => tehsils.filter((t) => t.cityId === cityId);
export const getTehsil = (cityId: string, id: string): Tehsil | undefined =>
  tehsils.find((t) => t.cityId === cityId && t.id === id);

/* ------------------------------------------------------------------------- rows */

const rowIndex = new Map<string, { row: RateRow; cityId: string; schedule: RateSchedule }>();
for (const s of schedules) for (const row of s.rows) rowIndex.set(row.id, { row, cityId: s.cityId, schedule: s });

export const getRateRow = (id: string) => rowIndex.get(id)?.row;
export const getRateRowWithSchedule = (id: string) => rowIndex.get(id);

/** All rows of one tehsil in the city's current schedule, in printed serial order. */
export function getRowsByTehsil(cityId: string, tehsilId: string): RateRow[] {
  const s = getCurrentRateSchedule(cityId);
  if (!s) return [];
  return s.rows.filter((r) => r.sro === tehsilId).sort((a, b) => a.serial - b.serial);
}

export function getRoadSegmentsByTehsil(cityId: string, tehsilId: string): RoadSegmentRow[] {
  const s = getCurrentRateSchedule(cityId);
  if (!s) return [];
  return s.roadSegments.filter((r) => r.sro === tehsilId);
}

/** Road segments that run through one village row. */
export function getRoadSegmentsForRow(cityId: string, rateRowId: string): RoadSegmentRow[] {
  const s = getCurrentRateSchedule(cityId);
  if (!s) return [];
  return s.roadSegments.filter((r) => r.rateRowId === rateRowId);
}

/** Row by its slug within a tehsil — how the village page resolves its URL. */
export function getRowBySlug(cityId: string, tehsilId: string, slug: string): RateRow | undefined {
  return getRowsByTehsil(cityId, tehsilId).find((r) => r.slug === slug);
}

/* -------------------------------------------------------------------- road bands */

/**
 * The road-width columns a city's list prints, cheapest first.
 *
 * Ayodhya prints three and Lucknow four, so nothing may assume a fixed set. Everything that reads
 * a land rate goes through these three helpers rather than naming a key.
 */
export function getRoadBands(cityId: string): RoadBand[] {
  return getCurrentRateSchedule(cityId)?.roadBands ?? [];
}

/** The bands this row actually prints, in the schedule's order. Some rows fill only the first. */
export function bandsForRow(cityId: string, row: RateRow): { band: RoadBand; rate: number }[] {
  return getRoadBands(cityId)
    .filter((b) => typeof row.nonAgri[b.key] === "number")
    .map((b) => ({ band: b, rate: row.nonAgri[b.key] }));
}

/**
 * The row's cheapest printed land rate -- the narrowest road band it carries.
 *
 * This is what a page leads with, what the tehsil median is taken over and what two rows are
 * compared on, because it is the one column every row has. It replaced `row.nonAgri.lt9m`, which
 * was the same thing while three fixed keys were the only possibility.
 */
export function baseRate(row: RateRow): number {
  // Band order comes from the schedule, not from the order the keys happen to sit in the JSON.
  const bands = rowIndex.get(row.id)?.schedule.roadBands ?? [];
  for (const b of bands) {
    const v = row.nonAgri[b.key];
    if (typeof v === "number") return v;
  }
  return 0;
}

/** One band's rate, or null where this row does not print that column. */
export function rateForBand(row: RateRow, key: string): number | null {
  const v = row.nonAgri[key];
  return typeof v === "number" ? v : null;
}

/**
 * The date the list covering this SRO took effect.
 *
 * A district does not revise every SRO on one day. Lucknow's seven transcribed SROs are all
 * 01-08-2025, but Malihabad's list is dated 31-12-2025, so once it lands the city will carry two
 * dates at once and a page that printed the city's date would be wrong for a third of its rows.
 * The SRO's own date wins where the source doc carries one.
 */
export function rowEffectiveFrom(schedule: RateSchedule, sro: string): string {
  return schedule.sourceDocs.find((d) => d.sro === sro)?.effectiveFrom ?? schedule.effectiveFrom;
}

/** The Collector's order date for this SRO's list, same rule as rowEffectiveFrom. */
export function rowOrderDate(schedule: RateSchedule, sro: string): string {
  return schedule.sourceDocs.find((d) => d.sro === sro)?.orderDate ?? schedule.orderDate;
}

/* -------------------------------------------------------------------- summaries */

const median = (xs: number[]): number | null => {
  if (xs.length === 0) return null;
  const s = [...xs].sort((a, b) => a - b);
  const m = s.length % 2 ? s[(s.length - 1) / 2] : (s[s.length / 2 - 1] + s[s.length / 2]) / 2;
  return Math.round(m);
};

export type TehsilSummary = {
  tehsil: Tehsil;
  rowCount: number;
  segmentCount: number;
  /** ₹ per sq m, across the <9 m column, which is the base rate every row carries */
  minNonAgri: number | null;
  maxNonAgri: number | null;
  medianNonAgri: number | null;
  /** highest ₹ per sq m on any road segment in this tehsil */
  topSegmentRate: number | null;
};

export function getTehsilSummary(cityId: string, tehsilId: string): TehsilSummary | null {
  const tehsil = getTehsil(cityId, tehsilId);
  if (!tehsil) return null;
  const rows = getRowsByTehsil(cityId, tehsilId);
  const segments = getRoadSegmentsByTehsil(cityId, tehsilId);
  const base = rows.map((r) => r.nonAgri.lt9m);
  return {
    tehsil,
    rowCount: rows.length,
    segmentCount: segments.length,
    minNonAgri: base.length ? Math.min(...base) : null,
    maxNonAgri: base.length ? Math.max(...base) : null,
    medianNonAgri: median(base),
    topSegmentRate: segments.length ? Math.max(...segments.map((s) => s.nonAgri)) : null,
  };
}

export const getTehsilMedian = (cityId: string, tehsilId: string) => median(getRowsByTehsil(cityId, tehsilId).map((r) => r.nonAgri.lt9m));

/**
 * Nearest rows by rate similarity within the same tehsil (spec: "6 nearest villages in the same
 * tehsil by rate similarity"). Compared on the <9 m base rate, which every row has.
 */
export function getSimilarRows(cityId: string, row: RateRow, count = 6): RateRow[] {
  return getRowsByTehsil(cityId, row.sro)
    .filter((r) => r.id !== row.id)
    .map((r) => ({ r, d: Math.abs(r.nonAgri.lt9m - row.nonAgri.lt9m) }))
    .sort((a, b) => a.d - b.d || a.r.serial - b.r.serial)
    .slice(0, count)
    .map((x) => x.r);
}

/* ------------------------------------------------------------------- indexing */

const indexableIds = new Set(indexable.rateRowIds);

/**
 * A village page is indexable when a live locality points at its row, or when it has been opened
 * by hand in data/rates/indexable.json. Everything else builds but ships noindex and stays out of
 * the sitemaps (Step 9, section C3).
 */
export function isRowIndexable(rateRowId: string, referencedByLiveLocality: boolean): boolean {
  return referencedByLiveLocality || indexableIds.has(rateRowId);
}

/**
 * Rows whose rate profile is unique within their SRO, per city.
 *
 * Ayodhya decides indexability from its written content: 866 of 1,630 rows have page copy that
 * says something the schedule alone does not, and those are the ones opened to search. Lucknow has
 * no written content yet, so that allowlist would leave all 1,449 of its pages noindex.
 *
 * What can be decided from the list itself is whether a page is a duplicate. The district prices
 * by band, so dozens of rows in one SRO can carry an identical set of figures; a page repeating
 * another page's numbers under a different name is thin by definition. A row whose profile is its
 * own in its SRO is not, so it is indexable. This is the same grouping getRateBands uses for the
 * "rate bands" section, read for a different purpose.
 *
 * It is a weaker test than having written copy, and the rows it opens carry only the published
 * figures. When Lucknow's page content is written this should give way to an allowlist, as
 * Ayodhya's did.
 */
const uniqueProfileIds = (() => {
  const out = new Map<string, Set<string>>();
  for (const s of schedules) {
    const ids = new Set<string>();
    const bySro = new Map<string, Map<string, string[]>>();
    for (const row of s.rows) {
      const profile = [
        ...s.roadBands.map((b) => row.nonAgri[b.key] ?? "-"),
        row.commercial?.shop ?? "-",
        row.commercial?.office ?? "-",
        row.commercial?.godown ?? "-",
        row.covered?.ordinary ?? "-",
        row.covered?.premium ?? "-",
        row.agriLakhPerHa.general ?? "-",
      ].join("|");
      if (!bySro.has(row.sro)) bySro.set(row.sro, new Map());
      const m = bySro.get(row.sro)!;
      if (!m.has(profile)) m.set(profile, []);
      m.get(profile)!.push(row.id);
    }
    for (const m of bySro.values()) for (const group of m.values()) if (group.length === 1) ids.add(group[0]);
    out.set(s.cityId, ids);
  }
  return out;
})();

/** True where this row's figures are not repeated by another row of the same SRO. */
export const hasUniqueRateProfile = (cityId: string, rateRowId: string): boolean =>
  uniqueProfileIds.get(cityId)?.has(rateRowId) ?? false;

export const getIndexableRowIds = () => indexableIds;

/* ------------------------------------------------------- locality rate view */

/**
 * The three-number view of a locality's circle rate, from whichever source it has.
 *
 * A locality either points into the published list through `rateRefs` or, for a city whose list
 * is not transcribed yet, carries the older `circleRate` object. Everything that needs one
 * headline figure — the meta description, the OG image, the source stamp — must go through here,
 * or a locality with real rows would still be described by its seed placeholder.
 *
 * Where a locality spans several rows the highest of each column wins, matching
 * scripts/derive-circle-rates.ts. The full range is on the locality page and the village pages.
 */
export type LocalityRate = {
  /** ₹ per sq m */
  residential: number;
  /** ₹ per sq m */
  commercial: number;
  /** ₹ per hectare, or null where the list prints no agricultural figure (urban rows) */
  agricultural: number | null;
  effectiveFrom: string;
  sourceUrl: string;
  /** true when this came from the published list rather than the legacy field */
  fromRateList: boolean;
};

export function getLocalityRate(locality: {
  cityId: string;
  rateRefs?: { rateRowId: string }[];
  circleRate?: { residential: number; commercial: number; agricultural: number; effectiveFrom: string; sourceUrl: string };
}): LocalityRate | undefined {
  const refs = locality.rateRefs ?? [];
  if (refs.length > 0) {
    const rows = refs.flatMap((r) => {
      const hit = rowIndex.get(r.rateRowId);
      return hit ? [hit] : [];
    });
    if (rows.length > 0) {
      const schedule = rows[0].schedule;
      const agri = rows.map((x) => x.row.agriLakhPerHa.general).filter((v) => v !== null);
      return {
        residential: Math.max(...rows.map((x) => baseRate(x.row))),
        commercial: Math.max(...rows.map((x) => x.row.commercial?.shop ?? 0), 1),
        agricultural: agri.length > 0 ? Math.max(...agri) * 100_000 : null,
        effectiveFrom: schedule.effectiveFrom,
        sourceUrl: schedule.sourceDocs[0].archiveUrl ?? schedule.sourceDocs[0].igrsupUrl,
        fromRateList: true,
      };
    }
  }
  if (!locality.circleRate) return undefined;
  return { ...locality.circleRate, fromRateList: false };
}

/* ---------------------------------------------------------------------- units */

export const getUnits = () => units;
export const getValuationRules = () => valuationRules;

/**
 * Villages in a tehsil that share an identical set of rates.
 *
 * The district sets rates by band rather than per village: 1,630 rows across Ayodhya carry only
 * about 600 distinct rate sets, and in the rural tehsils a single set can cover dozens of
 * villages. Listing the rates once with the villages under them says that plainly, where a table
 * of 351 rows repeating the same four figures hides it.
 *
 * Bands are ordered by size, largest first, and a band of one is not a band — those villages are
 * left to the full table above.
 */
export function getRateBands(cityId: string, tehsilId: string): { key: string; rows: RateRow[] }[] {
  const groups = new Map<string, RateRow[]>();
  const roadBands = getRoadBands(cityId);
  for (const row of getRowsByTehsil(cityId, tehsilId)) {
    const key = [
      // Every band this schedule declares, so two rows are only alike when all their columns are.
      ...roadBands.map((b) => row.nonAgri[b.key] ?? "-"),
      row.commercial?.shop ?? "-",
      row.commercial?.office ?? "-",
      row.commercial?.godown ?? "-",
      row.agriLakhPerHa.general ?? "-",
    ].join("|");
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key)!.push(row);
  }
  return [...groups.entries()]
    .filter(([, rows]) => rows.length > 1)
    .map(([key, rows]) => ({ key, rows }))
    .sort((a, b) => b.rows.length - a.rows.length);
}
