/**
 * Copy for the plot yield calculator. Written per language, not translated. Imports no data (the
 * calculator is a client component).
 */
import type { Locale } from "./i18n";
import type { YieldAreaUnit } from "./yield";

const copy = {
  en: {
    inputsTitle: "Your plot",
    place: "Locality",
    optional: "optional",
    placePlaceholder: "Village, mohalla or colony, e.g. Chinhat",
    placeHint: "Pick one to use its circle rate. Leave blank to work from your price alone.",
    loading: "Loading the list…",
    loadFailed: "The list could not be loaded. You can still use the calculator without a locality.",
    listLabel: "Suggestions",
    placeRates: "Circle rate for this plot",
    placeAwaited: "Circle rates for this SRO are not on the site yet, so stamp duty is worked out on your price.",
    clearPlace: "Clear",
    area: "Plot size",
    unit: "Unit",
    roadWidth: "Road width at the plot",
    landKind: "Land type",
    landPlot: "Plot (non-agricultural)",
    landFarm: "Farmland (agricultural)",
    price: "Purchase price",
    priceTotal: "Total ₹",
    pricePerSqft: "₹ per sq ft",
    priceIs: "Total price",
    buyer: "Buyer",
    brokerLegal: "Broker, legal and other costs",
    years: "Holding period",
    yearsUnit: "years",
    appreciation: "Expected yearly appreciation",
    presetsNote: "These are assumptions you choose, not our forecast.",
    presetCautious: "Cautious",
    presetModerate: "Moderate",
    presetStrong: "Strong",
    income: "Yearly income from the plot",
    incomeHint: "Farming lease or rent, ₹ per year. Leave blank if none.",
    incomeGrowth: "Yearly growth of that income",
    holding: "Yearly holding cost",
    holdingHint: "Boundary wall upkeep, a guard, property tax: ₹ per year.",
    selling: "Selling costs at exit",
    fdRate: "Fixed deposit rate, for comparison",
    perYear: "a year",

    resultsTitle: "What it could return",
    beforeTax: "Before tax",
    totalCost: "Total cost in",
    exitValue: "Value at exit",
    exitValueNote: "after selling costs",
    netProfit: "Net profit",
    cagr: "CAGR",
    irr: "IRR",
    notApplicable: "—",
    circleNote: "Stamp duty will be on the circle value {value}, not your price.",
    circleValue: "Circle value",
    breakdown: "How the cost in adds up",
    purchasePrice: "Price",
    stampDuty: "Stamp duty",
    registration: "Registration fee",
    brokerLegalShort: "Broker and legal",
    multiple: "Profit multiple",
    totalIncome: "Income received",
    holdingTotal: "Holding costs paid",
    grossYield: "Gross yield, year 1",
    fdLine: "The same {cost} in a fixed deposit at {rate}% for {years} years: {value}, a profit of {profit}.",
    fdBetter: "On these assumptions the FD comes out ahead.",
    plotBetter: "On these assumptions the plot comes out ahead.",
    tableTitle: "Year by year",
    year: "Year",
    value: "Plot value",
    incomeCol: "Income",
    cumulative: "Cumulative cash",
    chartTitle: "Plot value against the same money in an FD",
    chartPlot: "Plot value",
    chartFd: "Fixed deposit",
    taxTitle: "What about tax?",
    taxBody:
      "These figures are before tax. Capital gains tax may apply when you sell. Agricultural land in a rural area may not count as a capital asset, so its sale can be exempt; urban plots and land inside municipal limits generally are not. Income from farming the land is treated differently from rent. The rules depend on where the land is and how long you hold it, so check with a chartered accountant before you rely on a net figure.",
    download: "Download summary (PDF)",
    share: "Share",
    copied: "Link copied",
    whatsapp: "Discuss this plot with our broker",
    disclaimer: "Illustration only, based on the assumptions you entered. Land prices can fall. Not investment advice.",
    estimateNote: "Stamp duty and registration use the site's current UP rates, which are still being confirmed against the notification.",
    printInputs: "Assumptions",
    fallback: "The calculator needs JavaScript. Circle rates for every village are on the city circle-rate pages:",
  },
  hi: {
    inputsTitle: "आपका प्लॉट",
    place: "इलाक़ा",
    optional: "वैकल्पिक",
    placePlaceholder: "गाँव, मोहल्ला या कॉलोनी, जैसे चिनहट",
    placeHint: "सर्किल रेट के लिए कोई चुनें। ख़ाली छोड़ें तो सिर्फ़ आपके दाम से हिसाब होगा।",
    loading: "सूची खुल रही है…",
    loadFailed: "सूची नहीं खुल पाई। इलाक़े के बिना भी कैलकुलेटर चलेगा।",
    listLabel: "सुझाव",
    placeRates: "इस प्लॉट का सर्किल रेट",
    placeAwaited: "इस एसआरओ की सर्किल रेट सूची अभी साइट पर नहीं है, इसलिए स्टाम्प ड्यूटी आपके दाम पर निकाली गई है।",
    clearPlace: "हटाएँ",
    area: "प्लॉट का आकार",
    unit: "इकाई",
    roadWidth: "प्लॉट के सामने सड़क की चौड़ाई",
    landKind: "ज़मीन का प्रकार",
    landPlot: "प्लॉट (अकृषिक)",
    landFarm: "खेती की ज़मीन (कृषि)",
    price: "ख़रीद का दाम",
    priceTotal: "कुल ₹",
    pricePerSqft: "₹ प्रति वर्ग फ़ुट",
    priceIs: "कुल दाम",
    buyer: "ख़रीदार",
    brokerLegal: "ब्रोकर, वकील और अन्य ख़र्च",
    years: "कितने साल रखेंगे",
    yearsUnit: "साल",
    appreciation: "सालाना बढ़त का अनुमान",
    presetsNote: "ये अनुमान आप चुनते हैं, यह हमारी भविष्यवाणी नहीं है।",
    presetCautious: "सतर्क",
    presetModerate: "मध्यम",
    presetStrong: "तेज़",
    income: "प्लॉट से सालाना आमदनी",
    incomeHint: "खेती का पट्टा या किराया, ₹ प्रति साल। न हो तो ख़ाली छोड़ें।",
    incomeGrowth: "उस आमदनी की सालाना बढ़त",
    holding: "सालाना रखरखाव ख़र्च",
    holdingHint: "बाउंड्री की मरम्मत, चौकीदार, संपत्ति कर: ₹ प्रति साल।",
    selling: "बेचते समय ख़र्च",
    fdRate: "तुलना के लिए एफ़डी की दर",
    perYear: "सालाना",

    resultsTitle: "यह कितना लौटा सकता है",
    beforeTax: "टैक्स से पहले",
    totalCost: "कुल लागत",
    exitValue: "बेचते समय मूल्य",
    exitValueNote: "बिक्री ख़र्च के बाद",
    netProfit: "शुद्ध मुनाफ़ा",
    cagr: "सीएजीआर",
    irr: "आईआरआर",
    notApplicable: "—",
    circleNote: "स्टाम्प ड्यूटी आपके दाम पर नहीं, सर्किल मूल्य {value} पर लगेगी।",
    circleValue: "सर्किल मूल्य",
    breakdown: "कुल लागत कैसे बनी",
    purchasePrice: "दाम",
    stampDuty: "स्टाम्प ड्यूटी",
    registration: "रजिस्ट्री शुल्क",
    brokerLegalShort: "ब्रोकर और वकील",
    multiple: "मुनाफ़े का गुणक",
    totalIncome: "मिली आमदनी",
    holdingTotal: "रखरखाव पर ख़र्च",
    grossYield: "पहले साल की सकल आय",
    fdLine: "यही {cost} {rate}% की एफ़डी में {years} साल: {value}, यानी {profit} का मुनाफ़ा।",
    fdBetter: "इन अनुमानों पर एफ़डी आगे रहती है।",
    plotBetter: "इन अनुमानों पर प्लॉट आगे रहता है।",
    tableTitle: "साल-दर-साल",
    year: "साल",
    value: "प्लॉट का मूल्य",
    incomeCol: "आमदनी",
    cumulative: "कुल नक़द",
    chartTitle: "प्लॉट का मूल्य बनाम एफ़डी में वही रक़म",
    chartPlot: "प्लॉट का मूल्य",
    chartFd: "एफ़डी",
    taxTitle: "टैक्स का क्या?",
    taxBody:
      "ये आँकड़े टैक्स से पहले के हैं। बेचने पर कैपिटल गेन टैक्स लग सकता है। ग्रामीण इलाक़े की कृषि भूमि पूँजीगत संपत्ति नहीं मानी जा सकती, इसलिए उसकी बिक्री छूट में आ सकती है; शहरी प्लॉट और नगर सीमा के भीतर की ज़मीन आम तौर पर नहीं। खेती की आमदनी और किराये को अलग तरह से देखा जाता है। नियम ज़मीन की जगह और कितने समय रखी गई इस पर निर्भर हैं, इसलिए शुद्ध आँकड़े पर भरोसा करने से पहले चार्टर्ड अकाउंटेंट से पूछें।",
    download: "सारांश डाउनलोड करें (पीडीएफ़)",
    share: "शेयर करें",
    copied: "लिंक कॉपी हो गया",
    whatsapp: "इस प्लॉट पर हमारे ब्रोकर से बात करें",
    disclaimer: "केवल उदाहरण, आपके दिए अनुमानों पर आधारित। ज़मीन के दाम गिर भी सकते हैं। यह निवेश सलाह नहीं है।",
    estimateNote: "स्टाम्प ड्यूटी और रजिस्ट्री शुल्क साइट पर दर्ज यूपी की मौजूदा दरों से हैं, जिनकी अधिसूचना से पुष्टि अभी बाक़ी है।",
    printInputs: "अनुमान",
    fallback: "कैलकुलेटर के लिए जावास्क्रिप्ट चाहिए। हर गाँव का सर्किल रेट शहर के सर्किल रेट पेज पर है:",
  },
} satisfies Record<Locale, Record<string, string>>;

export type YieldCopy = (typeof copy)["en"];
export const yc = (locale: Locale): YieldCopy => copy[locale];

export const yieldUnitLabel: Record<YieldAreaUnit, Record<Locale, string>> = {
  sqft: { en: "sq ft", hi: "वर्ग फ़ुट" },
  sqm: { en: "sq m", hi: "वर्ग मीटर" },
  sqyd: { en: "sq yd", hi: "वर्ग गज" },
  bigha: { en: "bigha", hi: "बीघा" },
  acre: { en: "acre", hi: "एकड़" },
  hectare: { en: "hectare", hi: "हेक्टेयर" },
};

export const buyerLabel: Record<"male" | "female" | "joint", Record<Locale, string>> = {
  male: { en: "Male", hi: "पुरुष" },
  female: { en: "Female", hi: "महिला" },
  joint: { en: "Joint", hi: "संयुक्त" },
};
