/**
 * npm run rates:village-redirects
 *
 * Writes a 301 for every village URL whose slug the written content superseded.
 *
 * The step 9 importer derived each slug with lib/devanagari.ts; the content carries a hand-checked
 * romanisation and wins (step 9b, point 1). 378 of the 1,630 differ — nearly all corrections, as
 * in amova to amowa or karaundimaphi to karaundimafi — and those URLs were already built, linked
 * from tehsil pages and in the sitemap, so they redirect rather than disappear.
 *
 * The block is written between markers in public/_redirects so the file's other rules survive a
 * re-run, and so a later list revision can regenerate it without hand-editing 756 lines.
 */
import fs from "node:fs";
import path from "node:path";
import { getAllVillageContent } from "../lib/village-content";
import schedule from "../data/rates/ayodhya-2025-06-07.json";
import tehsilsJson from "../data/tehsils.json";

const START = "# --- village slug redirects (generated by scripts/build-village-redirects.ts) ---";
const END = "# --- end village slug redirects ---";

function main() {
  const rows = new Map((schedule.rows as { id: string; slug: string; sro: string }[]).map((r) => [r.id, r]));
  const tehsilIds = new Set((tehsilsJson as { id: string; cityId: string }[]).filter((t) => t.cityId === "ayodhya").map((t) => t.id));

  const lines: string[] = [];
  let skipped = 0;
  for (const v of getAllVillageContent()) {
    const row = rows.get(v.rateRowId);
    if (!row || row.slug === v.slug) continue;
    // The SRO is the tehsil segment in the URL; skip anything whose tehsil has no page.
    if (!tehsilIds.has(v.sro)) {
      skipped++;
      continue;
    }
    for (const prefix of ["", "/hi"]) {
      lines.push(`${prefix}/ayodhya/circle-rates/${v.sro}/${row.slug}/ ${prefix}/ayodhya/circle-rates/${v.sro}/${v.slug}/ 301`);
    }
  }

  const file = path.join("public", "_redirects");
  const existing = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : "";
  const block = [START, ...lines, END].join("\n");
  const next =
    existing.includes(START) && existing.includes(END)
      ? existing.replace(new RegExp(`${START}[\\s\\S]*?${END}`), block)
      : `${existing.trimEnd()}\n\n${block}\n`;

  fs.writeFileSync(file, next.endsWith("\n") ? next : `${next}\n`);
  console.log(`ok   village redirects: ${lines.length} rule(s) for ${lines.length / 2} renamed slug(s)`);
  if (skipped > 0) console.warn(`warn ${skipped} renamed slug(s) skipped: their SRO has no tehsil record`);
}

main();
