/**
 * npm run rates:derive
 *
 * Regenerates data/circleRates.json from the full published lists in data/rates/ (Step 9, A3).
 * circleRates.json is the narrow, three-number-per-locality view the city hub, the locality key
 * facts and the stamp duty calculator still read; the full model lives in data/rates/.
 *
 *   residential  = the cheapest printed road band  ₹ per sq m
 *   commercial   = commercial.shop         ₹ per sq m
 *   agricultural = agriLakhPerHa.general × 100000   → ₹ per hectare
 *
 * Do not hand-edit data/circleRates.json. Cities without a transcribed list (Lucknow, Gorakhpur)
 * keep their existing seed schedule untouched: this script only replaces the schedules of cities
 * that have one, and says so in the summary.
 *
 * Wired into prebuild so a stale derived file cannot ship.
 */
import fs from "node:fs";
import path from "node:path";
import { z } from "zod";
import { circleRatesFileSchema, rateScheduleSchema, type CircleRateSchedule, type RateSchedule } from "../lib/schemas";

const LAKH = 100_000;

const ratesDir = path.join("data", "rates");
const circleRatesFile = path.join("data", "circleRates.json");

function readSchedules(): RateSchedule[] {
  if (!fs.existsSync(ratesDir)) return [];
  const out: RateSchedule[] = [];
  for (const f of fs.readdirSync(ratesDir).filter((f) => f.endsWith(".json") && f !== "indexable.json")) {
    const raw = JSON.parse(fs.readFileSync(path.join(ratesDir, f), "utf8"));
    const parsed = rateScheduleSchema.safeParse(raw);
    if (!parsed.success) {
      console.error(`data/rates/${f}:\n${z.prettifyError(parsed.error)}`);
      process.exit(1);
    }
    out.push(parsed.data);
  }
  return out;
}

function main() {
  const schedules = readSchedules();
  if (schedules.length === 0) {
    console.log("ok   rates:derive: no files in data/rates/, nothing to derive");
    return;
  }

  const localities = JSON.parse(fs.readFileSync(path.join("data", "localities.json"), "utf8")) as {
    id: string;
    cityId: string;
    tehsil?: string;
    rateRefs?: { rateRowId: string }[];
  }[];
  const existing = circleRatesFileSchema.parse(JSON.parse(fs.readFileSync(circleRatesFile, "utf8")));

  const derivedCities = new Set(schedules.map((s) => s.cityId));
  const kept = existing.filter((s) => !derivedCities.has(s.cityId));
  const derived: CircleRateSchedule[] = [];

  for (const schedule of schedules) {
    const byRowId = new Map(schedule.rows.map((r) => [r.id, r]));
    const rates: CircleRateSchedule["rates"] = [];

    for (const l of localities) {
      if (l.cityId !== schedule.cityId) continue;
      const refs = (l.rateRefs ?? []).map((r) => byRowId.get(r.rateRowId)).filter((r) => r !== undefined);
      if (refs.length === 0) continue;

      // A locality can span several rows. The narrow view takes the highest of each column, which
      // is the figure a buyer is most likely to be charged inside that locality; the full range is
      // shown on the locality page's "Circle rates here" block and on the village pages.
      const agri = refs.map((r) => r.agriLakhPerHa.general).filter((v) => v !== null);
      rates.push({
        localityId: l.id,
        tehsil: l.tehsil ?? refs[0].sro,
        // Cheapest printed band per row, then the dearest of those across the locality's rows.
        residential: Math.max(...refs.map((r) => schedule.roadBands.map((b) => r.nonAgri[b.key]).find((v) => typeof v === "number") ?? 0)),
        commercial: Math.max(...refs.map((r) => r.commercial?.shop ?? 0), 1),
        // agriLakhPerHa.general is null on urban rows; fall back so the narrow schema stays positive.
        agricultural: agri.length > 0 ? Math.max(...agri) * LAKH : 1,
        effectiveFrom: schedule.effectiveFrom,
        sourceUrl: schedule.sourceDocs[0].igrsupUrl,
      });
    }

    if (rates.length === 0) {
      console.warn(`warn rates:derive: ${schedule.cityId} has a rate list but no locality carries rateRefs — keeping the existing schedule`);
      const prior = existing.find((s) => s.cityId === schedule.cityId);
      if (prior) kept.push(prior);
      continue;
    }

    derived.push({
      id: `${schedule.cityId}-${schedule.effectiveFrom}`,
      cityId: schedule.cityId,
      effectiveFrom: schedule.effectiveFrom,
      sourceUrl: schedule.sourceDocs[0].igrsupUrl,
      archiveUrl: schedule.sourceDocs[0].archiveUrl,
      units: { residential: "sqm", commercial: "sqm", agricultural: "hectare" },
      rates,
      sources: schedule.sources,
      updatedAt: schedule.updatedAt,
      todo: [
        "GENERATED by scripts/derive-circle-rates.ts from data/rates/. Do not hand-edit; edit the rate list or scripts/rate-aliases.json and re-run `npm run rates:derive`.",
        "Only localities carrying rateRefs appear here. Fill more entries in scripts/rate-aliases.json to widen the table.",
        `Agricultural is agriLakhPerHa.general × ${LAKH}; rows whose general column is blank (urban) carry a placeholder of 1 ₹/hectare and must not be quoted.`,
      ],
    });
  }

  const out = [...derived, ...kept].sort((a, b) => a.cityId.localeCompare(b.cityId) || b.effectiveFrom.localeCompare(a.effectiveFrom));
  circleRatesFileSchema.parse(out);
  fs.writeFileSync(circleRatesFile, `${JSON.stringify(out, null, 2)}\n`);

  console.log(`ok   rates:derive: ${derived.length} schedule(s) derived, ${kept.length} kept as-is`);
  for (const s of derived) console.log(`       ${s.cityId} @ ${s.effectiveFrom}: ${s.rates.length} localities from the published list`);
  for (const s of kept) console.log(`       ${s.cityId} @ ${s.effectiveFrom}: ${s.rates.length} localities (seed, no transcribed list)`);
}

main();
